# 1. Implement the K-mean clustering algorithm and test the algorithm using any data set of your choice. The output should include Accuracy, Error rate, Precision, and recall rate along with the confusion matrix.

# For 3 clusters

In [ ]:
# NAME:BOGGAVARAPU SHIVANI
# REG NO:20BCE0563

In [1]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix


In [2]:
iris = load_iris()
X = iris.data
y = iris.target

In [3]:
kmeans = KMeans(n_clusters=3, random_state=0)

In [4]:
kmeans.fit(X)

C:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=3, random_state=0)

In [5]:
y_pred = kmeans.predict(X)

In [6]:
accuracy = accuracy_score(y, y_pred)
precision = precision_score(y, y_pred, average=None)
recall = recall_score(y, y_pred, average=None)
confusion_mat = confusion_matrix(y, y_pred)

In [8]:
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("Confusion matrix:\n", confusion_mat)

Accuracy:  0.24
Precision:  [0.         0.         0.94736842]
Recall:  [0.   0.   0.72]
Confusion matrix:
 [[ 0 50  0]
 [48  0  2]
 [14  0 36]]


# Implement Principal Component Analysis (PCA) using any data set of your choice.The output should include Accuracy, Error rate, Precision, and recall rate along with the confusion matrix.

In [10]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [11]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [12]:
# Standardize the data
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

In [13]:
# Compute the covariance matrix
covariance_matrix = np.cov(X_std.T)

In [14]:
# Compute the eigenvectors and eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

In [15]:
# Sort the eigenvectors by their corresponding eigenvalues in descending order
sorted_indices = eigenvalues.argsort()[::-1]
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]


In [16]:
# Choose the top k eigenvectors that explain the most variance in the data
k = 2
projection_matrix = sorted_eigenvectors[:, :k]

In [17]:
# Project the original data onto the reduced space
X_pca = X_std.dot(projection_matrix)

In [18]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=0)

In [19]:
# Fit a logistic regression model to the training data
model = LogisticRegression(random_state=0)
model.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [20]:
# Predict the class labels for the test data
y_pred = model.predict(X_test)

In [21]:
# Evaluate the results using accuracy, precision, recall, and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
confusion_mat = confusion_matrix(y_test, y_pred)

In [22]:
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("Confusion matrix:\n", confusion_mat)

Accuracy:  0.8666666666666667
Precision:  [1.         0.90909091 0.625     ]
Recall:  [1.         0.76923077 0.83333333]
Confusion matrix:
 [[11  0  0]
 [ 0 10  3]
 [ 0  1  5]]
